### ISSUE TITLE
Should not require journald

### ISSUE THREAD

**Issue by khaytsus** [K2DLS/noaacap#2]
Not everyone uses or wants journald, surely there is a more agnostic way to log to syslog and let systemd intercept it like normal if it's in use.

**Comment by K2DLS** [comment]
Thank you for your input.  This was designed with a modern Debian or Raspbian in mind.  systemd-journald is provided by default and it was a conscious implementation decision to use it.  Since this is not a bug the issue will be closed.

**Comment by khaytsus** [comment]
I've ran an APRS iGate on a Pi for about 3 years, and it's on wheezy which is before journald.  But whatever, I just commented out all of the log items.

**Comment by K2DLS** [comment]
I'm glad you were able to adapt the code to your preference.  That is the power of open source.

You may be unaware that wheezy went end of life on May 31, 2018.  This means that security patches will be generally unavailable.  You ought to consider upgrading to a supported platform.

For more information see:

https://wiki.debian.org/LTS/
